drop table if exists assignee_domain CASCADE;
drop table if exists task_domain CASCADE;
drop table if exists tasks_assignees CASCADE;

create table assignee_domain (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table task_domain (id bigint generated by default as identity, completed boolean not null, date_time_set timestamp not null, title varchar(255) not null, primary key (id));
create table tasks_assignees (task_id bigint not null, assignee_id bigint not null, primary key (task_id, assignee_id));

alter table tasks_assignees add constraint FKo6dt3oc6eqa9fgnddu848oaof foreign key (assignee_id) references assignee_domain;
alter table tasks_assignees add constraint FKk03ucgrqykfih3rh4bc75a4i1 foreign key (task_id) references task_domain;